# Generated by Django 5.0.14 on 2026-05-25 18:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('source_name', models.CharField(max_length=255)),
                ('activity_type', models.CharField(max_length=255)),
                ('fuel_type', models.CharField(blank=True, max_length=255)),
                ('unit', models.CharField(max_length=50)),
                ('factor_value', models.DecimalField(decimal_places=8, max_digits=20)),
                ('factor_unit', models.CharField(max_length=50)),
                ('region', models.CharField(blank=True, max_length=255)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('ghg_protocol_category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=255)),
                ('target_model', models.CharField(max_length=100)),
                ('target_id', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=50)),
                ('record_id', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_user_logs', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.client')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(max_length=50)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_payload_ref', models.CharField(blank=True, max_length=500, null=True)),
                ('raw_line_number', models.IntegerField(default=0)),
                ('row_count_total', models.IntegerField(default=0)),
                ('row_count_success', models.IntegerField(default=0)),
                ('row_count_failed', models.IntegerField(default=0)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_jobs', to='my_app.client')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='analyst', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bio', models.TextField(blank=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.client')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RawSAPRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('WERKS', models.CharField(blank=True, max_length=50, null=True)),
                ('MATNR', models.CharField(blank=True, max_length=50, null=True)),
                ('MENGE', models.FloatField(blank=True, null=True)),
                ('MEINS', models.CharField(blank=True, max_length=50, null=True)),
                ('WRBTR', models.FloatField(blank=True, null=True)),
                ('WAERS', models.CharField(blank=True, max_length=10, null=True)),
                ('BLDAT', models.DateField(blank=True, null=True)),
                ('BKTXT', models.CharField(blank=True, max_length=255, null=True)),
                ('KOSTL', models.CharField(blank=True, max_length=50, null=True)),
                ('LIFNR', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_line_number', models.IntegerField()),
                ('ingestion_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.ingestionjob')),
            ],
        ),
        migrations.CreateModel(
            name='RawTravelRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingestion_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.ingestionjob')),
            ],
        ),
        migrations.CreateModel(
            name='RawUtilityRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingestion_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.ingestionjob')),
            ],
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP', 'SAP'), ('UTILITY', 'Utility'), ('TRAVEL', 'Travel')], max_length=50)),
                ('source_row_id', models.UUIDField()),
                ('source_row_model', models.CharField(max_length=255)),
                ('scope', models.CharField(choices=[('1', 'Scope 1'), ('2', 'Scope 2'), ('3', 'Scope 3')], max_length=1)),
                ('category', models.CharField(max_length=255)),
                ('activity_value', models.DecimalField(decimal_places=6, max_digits=20)),
                ('activity_unit', models.CharField(max_length=50)),
                ('activity_description', models.TextField()),
                ('activity_date', models.DateField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('emission_factor', models.DecimalField(decimal_places=8, max_digits=20)),
                ('emission_factor_source', models.CharField(max_length=255)),
                ('emission_factor_unit', models.CharField(max_length=50)),
                ('co2e_tonnes', models.DecimalField(decimal_places=8, max_digits=20)),
                ('calculation_method', models.CharField(max_length=255)),
                ('site_code', models.CharField(blank=True, max_length=255)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('FLAGGED', 'Flagged'), ('REJECTED', 'Rejected')], default='PENDING', max_length=50)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('is_manually_edited', models.BooleanField(default=False)),
                ('original_values', models.JSONField(blank=True, null=True)),
                ('is_flagged_anomaly', models.BooleanField(default=False)),
                ('anomaly_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='my_app.client')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_emissions', to=settings.AUTH_USER_MODEL)),
                ('ingestion_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='my_app.ingestionjob')),
            ],
            options={
                'ordering': ['-activity_date'],
                'indexes': [models.Index(fields=['client', 'scope', 'review_status'], name='my_app_emis_client__335da2_idx'), models.Index(fields=['client', 'activity_date'], name='my_app_emis_client__531a3b_idx'), models.Index(fields=['ingestion_job'], name='my_app_emis_ingesti_135467_idx')],
            },
        ),
    ]
