# Generated by Django 5.0.14 on 2026-05-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawsaprecord',
            name='is_parsed',
            field=models.BooleanField(default=False),
        ),
    ]
