# Generated by Django 5.0.14 on 2026-05-25 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_rawsaprecord_is_parsed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawsaprecord',
            old_name='ingestion_job',
            new_name='job',
        ),
    ]
