# Generated by Django 5.0.14 on 2026-05-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_rename_ingestion_job_rawsaprecord_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawtravelrecord',
            old_name='ingestion_job',
            new_name='job',
        ),
        migrations.RemoveField(
            model_name='rawtravelrecord',
            name='created_at',
        ),
        migrations.AddField(
            model_name='rawtravelrecord',
            name='cabin_class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rawtravelrecord',
            name='cost_amount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rawtravelrecord',
            name='cost_currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='rawtravelrecord',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawtravelrecord',
            name='destination',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rawtravelrecord',
            name='distance_km',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rawtravelrecord',
            name='expense_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rawtravelrecord',
            name='is_parsed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rawtravelrecord',
            name='origin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rawtravelrecord',
            name='raw_line_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rawtravelrecord',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawtravelrecord',
            name='trip_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rawtravelrecord',
            name='raw_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
