# Generated by Django 5.0.14 on 2026-05-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_rename_ingestion_job_rawtravelrecord_job_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawutilityrecord',
            old_name='ingestion_job',
            new_name='job',
        ),
        migrations.RemoveField(
            model_name='rawutilityrecord',
            name='created_at',
        ),
        migrations.AddField(
            model_name='rawutilityrecord',
            name='billing_period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawutilityrecord',
            name='billing_period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawutilityrecord',
            name='consumption_unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rawutilityrecord',
            name='consumption_value',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='rawutilityrecord',
            name='is_parsed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rawutilityrecord',
            name='meter_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rawutilityrecord',
            name='raw_line_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rawutilityrecord',
            name='site_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rawutilityrecord',
            name='raw_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
