# Generated by Django 5.0.14 on 2026-05-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_rename_ingestion_job_rawutilityrecord_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissionrecord',
            name='calculation_method',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='emissionrecord',
            name='emission_factor_source',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='emissionrecord',
            name='emission_factor_unit',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
