# Generated by Django 5.0.14 on 2026-05-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_alter_emissionrecord_calculation_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestionjob',
            name='error_log',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
