# Generated by Django 5.0.14 on 2026-05-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_ingestionjob_error_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestionjob',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
