# Generated by Django 5.0.14 on 2026-05-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_ingestionjob_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissionrecord',
            name='scope',
            field=models.CharField(choices=[('1', 'Scope 1'), ('2', 'Scope 2'), ('3', 'Scope 3')], max_length=20),
        ),
    ]
